language: node_js
node_js:
  - "4.1"
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install -y gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - "mkdir -p ~/.npm"
install:
  - sudo apt-get install --force-yes libbluetooth-dev
  - npm install -g node-gyp-install
  - node-gyp-install
  - npm install
env:
  - NODE_ENV=test
